### ISSUE TITLE
[SUPPORT] trousseau fails to reach a k8s Vault FQDN while working with IP

### ISSUE THREAD

**Issue by romdalf** [ondat/trousseau#38]
When Vault is deployed in Kubernetes as a StatefulSet, use the headless svc FQDN as Vault address in Trousseau's config file. Trousseau fails health probes and as a result, the container gets killed.

## Expected Behavior
When Vault is deployed in Kubernetes as a `Pod`, Trousseau should be able to send liveness probes using headless service reference, eg. `vault-internal.vault.svc.cluster.local`.

## Current Behavior
Liveness probes fail when using the headless svc FQDN or the Pod FQDN, but succeed when using Vault's Pod IP or FQDN of Vault server when deployed as external VM.

## Context (Environment)
Deploy Vault as a StatefulSet in a Kubernetes cluster.

**Comment by rovandep** [comment]
@vfiftyfive 

Is the Vault deployed with the same kubernetes cluster as Trousseau?

- [ ] yes; this is "fine" for demo only purposes but no for production - if the KMS is to be deployed within Kubernetes, it should be on a different one than Trousseau to avoid a circular dependency 
- [ ] no; this is the production-grade and expected deployment 

If yes; this is minor and should be address with low importance
If no; this is medium and should be address quickly to understand the root cause

**Comment by vfiftyfive** [comment]
Tested in the same cluster. I didn't test with Vault in a separate cluster, so I can't confirm if it is working or not at the moment. I'll test this scenario later on to set the expectations.

**Comment by rovandep** [comment]
I tried a couple of scenarios leading to the following error messages, any similar to yours: 

- [ ] `2022-02-22T15:52:27.416Z [ERROR] auth.kubernetes.auth_kubernetes_79abaffc: login unauthorized due to: Post "https://127.0.0.1:6443/apis/authentication.k8s.io/v1/tokenreviews": dial tcp 127.0.0.1:6443: connect: connection refused`

- [ ] `2022-02-22T15:58:53.810Z [ERROR] auth.kubernetes.auth_kubernetes_79abaffc: login unauthorized due to: Post "https://xxxxxx.trousseau.io:6443/apis/authentication.k8s.io/v1/tokenreviews": x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, localhost, xxxxxx, not xxxxxx.trousseau.io`

**Comment by vfiftyfive** [comment]
No, I don't have these errors, I don't have any error at all actually, which is why it's difficult to see where it's coming from.

**Comment by cptMikky** [comment]
We had reverse issue - it worked with FQDN but not with IP.  By trial, error and some dark magic we discovered that the issue was with Vault box certificate - CN and SAN didn't include the IP address so the SNI TLS failed. But there was no obvious error message where one would expect it (i.e. in Trousseau container logs).

Perhaps this is similar.

**Comment by rovandep** [comment]
Indeed, if you're using RKE2 or similar, tls-san entries have to be included within the config.yaml to ensure proper certificate creation.

**Comment by mhmxs** [comment]
I made a fix to log this kind of error properly. I hope it should help investigating what is going on.

https://github.com/ondat/trousseau/blob/1a9b3de8c94f81363b466ffe6da8a07e64696261/internal/server/health.go#L53
https://github.com/ondat/trousseau/blob/1a9b3de8c94f81363b466ffe6da8a07e64696261/internal/server/health.go#L62

The change is not merged to main, but we have a build to try: ghcr.io/ondat/trousseau:7800c0af4c15b5bd556c5a7144114afccfa5cced

**Comment by rovandep** [comment]
Note that this is an issue with k8s 1.21 introducing the certificate issuer validation when Kubernetes is trying to connect to Vault with its ServiceAccount. 
Depending on environment the certificate needs to include within the TLS-SAN values like all the control plane node FQDNs, IPs, and domain like:

tls-san:
  - "node01.sat.lab"
  - "node02.sat.lab"
  - "node03.sat.lab"
  - "sat.lab"

It is possible to bypass this validation by using the `disable_iss_validation=true` when writing the auth/kuberentes/config in Vault. 
See https://github.com/hashicorp/vault-helm/issues/562 

The logging would happen within the init container part with message like with a 403 and an explicit message like "certificate signed by an unknown authority".

With v1.1.3 (Thanks to @mhmxs) the logging part should be provide more insights.

I will keep this issue open for another 10 days - if no more comments I will close it.

**Comment by romdalf** [comment]
No other instances of this issue reported and logging instrument has been added to track the issue. 

Closing this issue for the moment.
