### ISSUE TITLE
[TASK] Review documentation

### ISSUE THREAD

**Issue by cannischan** [ondat/trousseau#45]
Ticket moved from JIRA: https://ondat.atlassian.net/browse/DOC-110

### Context
Review and write hashicorp documentation [GitHub - Trousseau-io/trousseau-io.github.io: Website content for the project trousseau.io](https://github.com/Trousseau-io/trousseau-io.github.io)

Documentation needs improvements in the number of Kubernetes distros supported with specific examples. Current documentation is not extensive enough and outdated or wrong in some areas.

It needs to be clear from the documentation that the vault token would need to be included as a file in all the controlplane nodes. 

### Acceptance Criteria
Review and write documentation for the hashicorp vault plugin

**Comment by cannischan** [comment]
@cvlc :
Can do! Here are some things that jump out for me from https://github.com/ondat/trousseau

:point_right: It would be great to have a logo of some kind. https://github.com/draios/oss-falco or https://github.com/strimzi/strimzi-kafka-operator can serve as examples, ideally we want a circle, hex or cube logo with a distinctive shape and colours and it would build into a distinct 'Ondat Open source' brand that we could theme future projects to. 
:point_right: Looking at the code, we've written this in a very extensible way. In order to drive community engagement it would be great to get Godocs integration, eg. See https://pkg.go.dev/github.com/bwmarrin/discordgo - with godocs, we can explain how the code works to make it easier for externals to contribute.
:point_right: It would be great to have a visual diagram of Trousseau's architecture and integration with Kubernetes and Vault, see https://github.com/external-secrets/kubernetes-external-secrets for inspiration. I notice there is a diagram in the assets folder of Trousseau that looks great, we should show it in the README!
:point_right: Like the above example, it would be great to have commands and examples for installing Trousseau and managing secrets.
:point_right: It would be great to have a helm chart and/or Kubernetes manifest to easily deploy and to make sure that the rendered chart or file is packaged with the Github release. 
:point_right: In terms of the overall structure, I feel like we could split out into a summary and architecture section, a technical documentation and installation section and a section on contributing, licensing and Ondat as a company. That said... 
:point_right: Rodney Karemba is working on some standards for how we present OSS projects externally - it'd be fantastic to align the project with them when he's had the opportunity to discuss and get feedback from the team!

**Comment by rovandep** [comment]
all right - let's have some checkpoints on where we are with the above:

- [ ] Documentation needs improvements in the number of Kubernetes distros supported with specific examples. Current documentation is not extensive enough and outdated or wrong in some areas.

- [ ] It needs to be clear from the documentation that the vault token would need to be included as a file in all the controlplane nodes.


- [ ] :point_right: It would be great to have a logo of some kind. https://github.com/draios/oss-falco or https://github.com/strimzi/strimzi-kafka-operator can serve as examples, ideally we want a circle, hex or cube logo with a distinctive shape and colours and it would build into a distinct 'Ondat Open source' brand that we could theme future projects to. 


- [ ] :point_right: Looking at the code, we've written this in a very extensible way. In order to drive community engagement it would be great to get Godocs integration, eg. See https://pkg.go.dev/github.com/bwmarrin/discordgo - with godocs, we can explain how the code works to make it easier for externals to contribute.


- [ ] :point_right: It would be great to have a visual diagram of Trousseau's architecture and integration with Kubernetes and Vault, see https://github.com/external-secrets/kubernetes-external-secrets for inspiration. I notice there is a diagram in the assets folder of Trousseau that looks great, we should show it in the README!


- [ ] :point_right: Like the above example, it would be great to have commands and examples for installing Trousseau and managing secrets.


- [ ] :point_right: It would be great to have a helm chart and/or Kubernetes manifest to easily deploy and to make sure that the rendered chart or file is packaged with the Github release. 


- [ ] :point_right: In terms of the overall structure, I feel like we could split out into a summary and architecture section, a technical documentation and installation section and a section on contributing, licensing and Ondat as a company. That said... 


- [ ] :point_right: @hubvu is working on some standards for how we present OSS projects externally - it'd be fantastic to align the project with them when he's had the opportunity to discuss and get feedback from the team!

**Comment by rovandep** [comment]
updated the above based on the latest work done on documentation

**Comment by romdalf** [comment]
A part from the DiscordGo thingy - all done. 
Closing this long standing issue.
